### ISSUE TITLE
Tipo de importação

### ISSUE THREAD

**Issue by ivanmirandaf** [southbridgeio/zabbix-review-export-import#8]
O script zabbix-import.py aceita apenas arquivos YAML?

**Comment by evgkrsk** [comment]
Yes, just as stated in README.

**Comment by ivanmirandaf** [comment]
Não entendi bem o README
Estou executando `python3 zabbix-import.py --zabbix-url http://localhost/zabbix --zabbix-username Admin --zabbix-password zabbix --debug --type host hosts/*` e no final eu tenho a mensagem:

2021-05-05 10:04:08,963 DEBUG    Loading from XML-exported YAML
2021-05-05 10:04:08,964 ERROR    TypeError('string indices must be integers',)
Traceback (most recent call last):
  File "zabbix-import.py", line 1780, in <module>
    maint_cache=maintenance2id,
  File "zabbix-import.py", line 1490, in main
    yml = yml["zabbix_export"]
TypeError: string indices must be integers
2021-05-05 10:04:08,980 ERROR    Some operations failed

**Comment by evgkrsk** [comment]
Please narrow down to one problematic input file and attach (or add link to) it and full debug output of zabbix-import.py.

Also, what python and OS version do you have?

**Comment by ivanmirandaf** [comment]
[log.txt](https://github.com/southbridgeio/zabbix-review-export-import/files/6427819/log.txt)

[RB260 - Almas.txt](https://github.com/southbridgeio/zabbix-review-export-import/files/6427832/RB260.-.Almas.txt)

Python 3.6.8
CentOS 7
Zabbix 5.0.11

**Comment by evgkrsk** [comment]
Please, try to import with code from **xml-import-detection-8** git branch (#9). **log.txt** is created without **--debug CLI** flag, please use it this time.

Obvious, you trying to import host from non-supported **XML** file instead on **YAML**, but at least we can print more clear error message in such case.

**Comment by ivanmirandaf** [comment]
Fiz a alteração no código mesmo assim o problema continua.
[log.txt](https://github.com/southbridgeio/zabbix-review-export-import/files/6429862/log.txt)

**Comment by evgkrsk** [comment]
As I say before, you trying to import from XML file, but only YAML is supported. Now clear message about that will be printed.
